language: c

branches:
    only:
        - master
        - /^test.*/
service:
    - docker

before_deploy:
  - >
      git_commit_id=$(git rev-parse --short HEAD)
      if [ "master" == "${TRAVIS_BRANCH}" ]; then
        image_tag="prod"
      else
        image_tag="stg"
      fi
      docker build -t pristtlt/test-jk:${image_tag}-${git_commit_id} .


deploy:
    privider: script
    script: bash script/docker_push.sh "pristtlt/test-jk:${image_tag}-${git_commit_id}"
