language: python

service:
    - docker
install:
    - echo ${TRAVIS_TAG}
    - echo ${TRAVIS_JOB_NAME}
    - echo ${TRAVIS_COMMIT}
    - echo ${TRAVIS_REPO_SLUG}
    - echo ${TRAVIS_PULL_REQUEST_SLUG}
    - docker build -t pristtlt/test-jk .

deploy:
    privider: script
    script: bash
      #install:
      # - >
      #     tag_commit_hash = "${TRAVIS_COMMIT}"
      #     docker build -t pristtlt/test-jk:"{}" .
      #deploy:
      #    provider: script
      #    script: bash script/docker_push.sh
      #    on:
      #        master
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #
      #
