language: bash
os: linux
dist: xenial

service:
    - docker

before_deploy:
  - >
    git_commit_id=$(git rev-parse --short HEAD);
    if [ "master" == "${TRAVIS_BRANCH}" ]; then
      image_tag="prod";
    else
      image_tag="stg";
    fi
    docker build -t pristtlt/test-jk:${image_tag}-${git_commit_id} .


deploy:
    privider: script
    script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push pristtlt/test-jk:${image_tag}-${git_commit_id}
    on:
        all_branches: true

