language: python
os: linux
dist: xenial

before_install:
    - echo "hello"

install:
    - echo index.html

script: true

before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "travis-auto-tags"
    - git config --local user.email "winewei@yeah.net"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
    - provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
          - index.html
      skip_cleanup: true
